[package]
name = "RobotCode2026"
version = "0.1.0"
edition = "2024"

[dependencies]
frcrs = "0.1.4"
nalgebra = "0.34.1"
serde_json = "1.0.145"
tokio = "1.47.1"
uom = "0.35.0"
serde = { version = "1.0.228", features = ["derive"] }
float-cmp = "0.10.0"
